In [18]:
#imports and data display structure things
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
import os
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 60)

In [ ]:
#PMJDY DATA
pmjdy_path = r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\raw\PMJDY.csv"
pmjdy_raw = pd.read_csv(pmjdy_path)
print("Shape:", pmjdy_raw.shape)
print("Columns:", pmjdy_raw.columns.tolist())
print("First 5 rows:")
pmjdy_raw.head(5)
# not using for now need state wise

Shape: (36, 10)
Columns: ['Country', 'Year', 'As On Date', 'Name Of The Bank', 'Types Of Banks', 'Accounts Opened In Rural Areas Under The Pradhan Mantri Jan Dhan Yojana (Pmjdy) By Various Banks (UOM:Number), Scaling Factor:1', 'Accounts Opened In Urban Areas Under The Pradhan Mantri Jan Dhan Yojana (Pmjdy) By Different Banks (UOM:Number), Scaling Factor:1', 'Number Of Beneficiaries (UOM:Number), Scaling Factor:1', 'The Cumulative Balance In Accounts (UOM:INR(IndianRupees)), Scaling Factor:100000', 'Rupay Debit Cards Issued By Each Bank (UOM:Number), Scaling Factor:1']
First 5 rows:

,Country,Year,As On Date,Name Of The Bank,Types Of Banks,"Accounts Opened In Rural Areas Under The Pradhan Mantri Jan Dhan Yojana (Pmjdy) By Various Banks (UOM:Number), Scaling Factor:1","Accounts Opened In Urban Areas Under The Pradhan Mantri Jan Dhan Yojana (Pmjdy) By Different Banks (UOM:Number), Scaling Factor:1","Number Of Beneficiaries (UOM:Number), Scaling Factor:1","The Cumulative Balance In Accounts (UOM:INR(IndianRupees)), Scaling Factor:100000","Rupay Debit Cards Issued By Each Bank (UOM:Number), Scaling Factor:1"
0,India,"Financial Year (Apr - Mar), 2026",11-Mar-2026,Axis Bank Ltd,Major Private Banks,206000,1248758,1454758,117905.63,908394
1,India,"Financial Year (Apr - Mar), 2026",11-Mar-2026,Bank of Baroda,Public Sector Banks,46053749,20196760,66250509,4150103.01,61287584
2,India,"Financial Year (Apr - Mar), 2026",11-Mar-2026,Bank of Baroda,Regional Rural Bank,21339242,3406968,24746210,1668228.11,10618719
3,India,"Financial Year (Apr - Mar), 2026",11-Mar-2026,Bank of India,Public Sector Banks,24247756,5271969,29519725,1773069.09,25902292
4,India,"Financial Year (Apr - Mar), 2026",11-Mar-2026,Bank of India,Regional Rural Bank,6257995,866576,7124571,207667.99,3391932

In [ ]:
#PMJDY statewise

pmjdy = pd.read_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\raw\PMJDY_statewise.csv")  


# Renamed columns to standard names
pmjdy.columns = [
    'sno', 'state_name', 'rural_accounts', 'urban_accounts',
    'total_accounts', 'total_balance_crore', 'rupay_cards'
]

#dropping last total row cause we dont need for statewise analysis
pmjdy = pmjdy[pmjdy['state_name'] != 'Total'].copy()

num_cols = ['rural_accounts', 'urban_accounts', 'total_accounts', 
            'total_balance_crore', 'rupay_cards']

for col in num_cols:
    pmjdy[col] = pd.to_numeric(
        pmjdy[col].astype(str).str.replace(',', '').str.strip(),
        errors='coerce'
    )


# Convert balance from crore to actual rupees
pmjdy['total_balance'] = pmjdy['total_balance_crore'] * 1e7

# Clean numeric columns
num_cols = ['rural_accounts', 'urban_accounts', 'total_accounts', 
            'total_balance', 'rupay_cards']
for col in num_cols:
    pmjdy[col] = pd.to_numeric(
        pmjdy[col].astype(str).str.replace(',', '').str.strip(),
        errors='coerce'
    )


# Derived variables
pmjdy['avg_balance_per_account'] = pmjdy['total_balance'] / pmjdy['total_accounts']
pmjdy['rupay_activation_ratio']  = pmjdy['rupay_cards']   / pmjdy['total_accounts']
pmjdy['rural_share']             = pmjdy['rural_accounts'] / pmjdy['total_accounts']
pmjdy['urban_share']             = pmjdy['urban_accounts'] / pmjdy['total_accounts']

print("Shape:", pmjdy.shape)
print("States:", pmjdy['state_name'].tolist())
pmjdy.head()
pmjdy.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleaned\PMJDY_state.csv", index=False)

Shape: (36, 12)
States: ['Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'The Dadra And Nagar Haveli And Daman And Diu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [22]:
#CENSUS DATA

census_path = r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\raw\census_2011.csv"

census_raw = pd.read_csv(census_path)


print("Shape:", census_raw.shape)
print("Columns:", census_raw.columns.tolist())
census_raw.head(3)

Shape: (606573, 92)
Columns: ['Country', 'State', 'District', 'Sub-District', 'Village Or Town Name', 'Year', 'Residence Type', 'Households (UOM:Number), Scaling Factor:1', 'Population (UOM:Number), Scaling Factor:1', 'Male Population (UOM:Number), Scaling Factor:1', 'Female Population (UOM:Number), Scaling Factor:1', 'Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1', 'Male Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1', 'Female Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1', 'Scheduled Caste Population (UOM:Number), Scaling Factor:1', 'Male Scheduled Caste Population (UOM:Number), Scaling Factor:1', 'Female Scheduled Caste Population  (UOM:Number), Scaling Factor:1', 'Scheduled Tribe Population (UOM:Number), Scaling Factor:1', 'Male Scheduled Tribe Population (UOM:Number), Scaling Factor:1', 'Female Scheduled Tribe Population  (UOM:Number), Scaling Factor:1', 'Literate Population  (UOM:Number), Scaling Factor:1', 'Male Literate Population (UOM:Number), Scaling Factor:1', 'Female Literate Population  (UOM:Number), Scaling Factor:1', 'Illiterate Population (UOM:Number), Scaling Factor:1', 'Male Illiterate Population  (UOM:Number), Scaling Factor:1', 'Female Illiterate Population  (UOM:Number), Scaling Factor:1', 'Working Population (UOM:Number), Scaling Factor:1', 'Male Working Population (UOM:Number), Scaling Factor:1', 'Female Woking Population (UOM:Number), Scaling Factor:1', 'Number Of Main Workers (UOM:Number), Scaling Factor:1', 'Number Of Male Main Workers (UOM:Number), Scaling Factor:1', 'Number Of Female Main Worker (UOM:Number), Scaling Factor:1', 'Number Of Main Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Male Main Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Female Main Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Male Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Female Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Main Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of Male Main Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of Female Main Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of  Main Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Male Main Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Female Main Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers  Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers  Who Worked For  3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers Who Worked For  3 To 6 Months (UOM:Number), Scaling Factor:1', 'Total Number Of Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of  Marginal Workers In Household Industry Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers In Household Industry Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers In Household Industry Who  Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers  Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers  Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers  Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Total Nuumber Of Marginal Workers As Agricultural Labour Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers In Agricultural Labour Who  Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Agricultural Labour Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers In Household Industry Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers In Household Industry Who  Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers In Household Industry Who  Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Male Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Female Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1', 'Number Of Non Workers (UOM:Number), Scaling Factor:1', 'Number Of Male Non Workers (UOM:Number), Scaling Factor:1', 'Number Of Female Non Workers (UOM:Number), Scaling Factor:1']

,Country,State,District,Sub-District,Village Or Town Name,Year,Residence Type,"Households (UOM:Number), Scaling Factor:1","Population (UOM:Number), Scaling Factor:1","Male Population (UOM:Number), Scaling Factor:1","Female Population (UOM:Number), Scaling Factor:1","Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1","Male Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1","Female Population In The Age Group 0 To 6 Years (UOM:Number), Scaling Factor:1","Scheduled Caste Population (UOM:Number), Scaling Factor:1","Male Scheduled Caste Population (UOM:Number), Scaling Factor:1","Female Scheduled Caste Population (UOM:Number), Scaling Factor:1","Scheduled Tribe Population (UOM:Number), Scaling Factor:1","Male Scheduled Tribe Population (UOM:Number), Scaling Factor:1","Female Scheduled Tribe Population (UOM:Number), Scaling Factor:1","Literate Population (UOM:Number), Scaling Factor:1","Male Literate Population (UOM:Number), Scaling Factor:1","Female Literate Population (UOM:Number), Scaling Factor:1","Illiterate Population (UOM:Number), Scaling Factor:1","Male Illiterate Population (UOM:Number), Scaling Factor:1","Female Illiterate Population (UOM:Number), Scaling Factor:1","Working Population (UOM:Number), Scaling Factor:1","Male Working Population (UOM:Number), Scaling Factor:1","Female Woking Population (UOM:Number), Scaling Factor:1","Number Of Main Workers (UOM:Number), Scaling Factor:1","Number Of Male Main Workers (UOM:Number), Scaling Factor:1","Number Of Female Main Worker (UOM:Number), Scaling Factor:1","Number Of Main Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Male Main Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Female Main Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Male Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Female Main Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Main Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Male Main Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Female Main Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Main Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Male Main Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Female Main Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Marginal Workers (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Cultivators (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Agricultural Labourers (UOM:Number), Scaling Factor:1","Number Of Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers In The Household Industry (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Other Workers (UOM:Number), Scaling Factor:1","Number Of Marginal Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Total Number Of Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Cultivators Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Agricultural Labour Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers In Household Industry Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers In Household Industry Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers In Household Industry Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Other Workers Who Worked For 3 To 6 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Cultivators Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Total Nuumber Of Marginal Workers As Agricultural Labour Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers In Agricultural Labour Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Agricultural Labour Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers In Household Industry Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers In Household Industry Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers In Household Industry Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Male Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Female Marginal Workers As Other Workers Who Worked For 0 To 3 Months (UOM:Number), Scaling Factor:1","Number Of Non Workers (UOM:Number), Scaling Factor:1","Number Of Male Non Workers (UOM:Number), Scaling Factor:1","Number Of Female Non Workers (UOM:Number), Scaling Factor:1"
0,India,Andaman And Nicobar Islands,Nicobars,Car Nicobar,Arong,"Calendar Year (Jan - Dec), 2011",Rural,233.0,1194.0,617.0,577.0,183.0,87.0,96.0,0.0,0.0,0.0,1117.0,584.0,533.0,887.0,475.0,412.0,307.0,142.0,165.0,527.0,349.0,178.0,506.0,343.0,163.0,10.0,7.0,3.0,4.0,3.0,1.0,177.0,131.0,46.0,315.0,202.0,113.0,21.0,6.0,15.0,1.0,0.0,1.0,0.0,0.0,0.0,11.0,0.0,11.0,9.0,6.0,3.0,19.0,6.0,13.0,1.0,0.0,1.0,0.0,0.0,0.0,9.0,0.0,9.0,9.0,6.0,3.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,667.0,268.0,399.0
1,India,Andaman And Nicobar Islands,Nicobars,Car Nicobar,Big Lapati,"Calendar Year (Jan - Dec), 2011",Rural,271.0,1098.0,584.0,514.0,133.0,68.0,65.0,0.0,0.0,0.0,1057.0,549.0,508.0,736.0,413.0,323.0,362.0,171.0,191.0,657.0,368.0,289.0,122.0,86.0,36.0,2.0,1.0,1.0,3.0,3.0,0.0,45.0,31.0,14.0,72.0,51.0,21.0,535.0,282.0,253.0,1.0,1.0,0.0,7.0,3.0,4.0,481.0,248.0,233.0,46.0,30.0,16.0,371.0,206.0,165.0,1.0,1.0,0.0,3.0,1.0,2.0,332.0,180.0,152.0,35.0,24.0,11.0,164.0,76.0,88.0,0.0,0.0,0.0,4.0,2.0,2.0,149.0,68.0,81.0,11.0,6.0,5.0,441.0,216.0,225.0
2,India,Andaman And Nicobar Islands,Nicobars,Car Nicobar,Chuckchucha,"Calendar Year (Jan - Dec), 2011",Rural,231.0,1021.0,536.0,485.0,109.0,60.0,49.0,0.0,0.0,0.0,485.0,243.0,242.0,677.0,372.0,305.0,344.0,164.0,180.0,287.0,244.0,43.0,155.0,136.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,155.0,136.0,19.0,132.0,108.0,24.0,0.0,0.0,0.0,1.0,0.0,1.0,17.0,1.0,16.0,114.0,107.0,7.0,132.0,108.0,24.0,0.0,0.0,0.0,1.0,0.0,1.0,17.0,1.0,16.0,114.0,107.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,734.0,292.0,442.0

In [23]:

# renamed columns without extra spaces
census_raw = census_raw.rename(columns={
    'State':                                                         'state_name',
    'Residence Type':                                                'residence_type',
    'Households (UOM:Number), Scaling Factor:1':                     'households',
    'Population (UOM:Number), Scaling Factor:1':                     'population',
    'Male Population (UOM:Number), Scaling Factor:1':                'male_pop',
    'Female Population (UOM:Number), Scaling Factor:1':              'female_pop',
    'Scheduled Caste Population (UOM:Number), Scaling Factor:1':     'sc_population',
    'Scheduled Tribe Population (UOM:Number), Scaling Factor:1':     'st_population',
    'Male Literate Population (UOM:Number), Scaling Factor:1':       'male_literate',
    'Working Population (UOM:Number), Scaling Factor:1':             'working_pop',
    'Female Woking Population (UOM:Number), Scaling Factor:1':       'female_working_pop',
    'Number Of Non Workers (UOM:Number), Scaling Factor:1':          'non_workers',
})

# rename columns with extra spaces 
census_raw = census_raw.rename(columns={
    'Literate Population  (UOM:Number), Scaling Factor:1':            'literate_pop',
    'Female Literate Population  (UOM:Number), Scaling Factor:1':     'female_literate',
})

#  filtered only needed columns
keep_cols = ['state_name', 'residence_type', 'households', 'population',
             'male_pop', 'female_pop', 'literate_pop', 'male_literate',
             'female_literate', 'sc_population', 'st_population',
             'working_pop', 'female_working_pop']

census = census_raw[keep_cols].copy()

# converted to numeric
num_cols = ['households', 'population', 'male_pop', 'female_pop',
            'literate_pop', 'male_literate', 'female_literate',
            'sc_population', 'st_population', 'working_pop', 'female_working_pop']
for col in num_cols:
    census[col] = pd.to_numeric(census[col], errors='coerce')



# aggregate from village to state level
census_state = census.groupby('state_name')[num_cols].sum().reset_index()

# derived variables
census_state['literacy_rate']        = (census_state['literate_pop']       / census_state['population']) * 100
census_state['male_literacy_rate']   = (census_state['male_literate']      / census_state['male_pop'])   * 100
census_state['female_literacy_rate'] = (census_state['female_literate']    / census_state['female_pop']) * 100
census_state['female_workforce_pct'] = (census_state['female_working_pop'] / census_state['female_pop']) * 100
census_state['sc_share']             = (census_state['sc_population']      / census_state['population']) * 100
census_state['st_share']             = (census_state['st_population']      / census_state['population']) * 100
census_state['avg_household_size']   = census_state['population']          / census_state['households']

# urban/rural split saved separately 
census_rural_urban = census.groupby(
    ['state_name', 'residence_type'])[num_cols].sum().reset_index()

census_state.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleaned/census_state.csv", index=False)
census_rural_urban.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleaned/census_rural_urban.csv", index=False)

In [24]:
# NFHS DATA
nfhs_path = r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\raw\NFHS.csv"
nfhs_raw = pd.read_csv(nfhs_path)
print("Shape:", nfhs_raw.shape)
print("Columns:", nfhs_raw.columns.tolist())
nfhs_raw.head(3)

Shape: (108, 136)
Columns: ['Country', 'State', 'Year', 'Residence Type', 'Nfhs Survey Number (Nfhs - 4 Or Nfhs - 5)', 'Women Having A Bank Or Savings Account That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1', 'Adolescent Fertility Rate For Women Age 15 To 19 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Age Group 15 To 49 Years Use Any Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Age Group 15 To 49 Years Any Modern Family Planning Method (%) (UOM:%(Percentage)), Scaling Factor:1', 'Average Out Of Pocket Expenditure For Each Delivery In Public Health Facility (UOM:INR(IndianRupees)), Scaling Factor:1', 'Births Attended By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1', 'Births Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1', 'Births In Private Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1', 'Births In Public Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1', 'Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Either Vaccination Card Or Mothers Recall (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Vaccination Card Only (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Diphtheria Tetanus Toxoids And Pertussis (Dtp) Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Hepatitis B Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Polio Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Rotavirus Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received Bacillus Calmette Guerin (Bcg) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Have Received The First Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Private Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Public Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 24 To 35 Months Who Have Received A Second Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 5 Years Who Attended Pre-Primary School During The Year 2019-20 (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 6 To 59 Months Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 6 To 8 Months Receiving Solid Or Semisolid Food And Breastmilk (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Age Group 9 To 35 Months Who Received Vitamin A Dose In The Last 6 Months (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Born At Home Who Were Taken To A Health Facility For A Check-Up Within 24 Hours Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under 5 Years Who Are Overweight (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under 5 Years Who Are Severely Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under 5 Years Who Are Stunted (Height-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under 5 Years Who Are Underweight (Weight-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under 5 Years Who Are Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under Age 3 Years Breastfed Within One Hour Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under Age 5 Years Whose Birth Was Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Under Age 6 Months Exclusively Breastfed (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children With Diarrhoea In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Oral Rehydration Salts (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Zinc (%) (UOM:%(Percentage)), Scaling Factor:1', 'Children With Fever Or Symptoms Of Acute Respiratory Infection In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Using Condom In The Age Group Of 15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Current Users Ever Told About Side Effects Of Current Method (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Age Group 15 To 49 Years Who Usually Participate In Three Household Decisions (%) (UOM:%(Percentage)), Scaling Factor:1', 'Deaths In The Last 3 Years Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1', 'Ever-Married Women Age Group 18 To 49 Years Who Have Ever Experienced Spousal Violence (%) (UOM:%(Percentage)), Scaling Factor:1', 'Ever-Married Women Age Group 18 To 49 Years Who Have Experienced Physical Violence During Any Pregnancy (%) (UOM:%(Percentage)), Scaling Factor:1', 'Female Population Age 6 Years And Above Who Ever Attended School (%) (UOM:%(Percentage)), Scaling Factor:1', 'Female Sterilization Married Women-15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Health Worker Ever Talked To Female Non-Users About Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1', 'Home Births That Were Conducted By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1', 'Households Using Clean Fuel For Cooking (%) (UOM:%(Percentage)), Scaling Factor:1', 'Households Using Iodized Salt (%) (UOM:%(Percentage)), Scaling Factor:1', 'Population And Household Profile-Households With Any Usual Member Covered Under A Health Insurance Or Financing Scheme (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Age Group 15 To 49 Years Using Intrauterine Device (Iud) Or Postpartum Intrauterine Contraceptive Device (Ppiud) As Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1', 'Infant Mortality Rate (Imr) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Of Age 15 To 49 Years Using Injectables As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1', 'Institutional Births (%) (UOM:%(Percentage)), Scaling Factor:1', 'Institutional Births In Public Facility (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Of Age 15 To 49 Years Using Male Sterlization As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 25 To 29 Years Married Before Age 21 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Who Are Overweight Or Obese (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Who Have Ever Used Internet (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Whose Body Mass Index (Bmi) Is Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Elevated Blood Pressure Or Taking Medicine To Control Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Who Consumed Iron Folic Acid For 100 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Who Consumed Iron Folic Acid For 180 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Who Had An Antenatal Check-Up In The First Trimester (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Who Had At Least 4 Antenatal Care Visits (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1', 'Mothers Whose Last Birth Was Protected Against Neonatal Tetanus (%) (UOM:%(Percentage)), Scaling Factor:1', 'Neonatal Mortality Rate (Nnmr) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Non-Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1', 'Non-Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Currently Married Women Age Group 15 To 49 Years Consuming Pill (%) (UOM:%(Percentage)), Scaling Factor:1', 'Population Below Age 15 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Population Living In Households That Use An Improved Sanitation Facility (%) (UOM:%(Percentage)), Scaling Factor:1', 'Population Living In Households With An Improved Drinking Water Source (%) (UOM:%(Percentage)), Scaling Factor:1', 'Population Living In Households With Electricity (%) (UOM:%(Percentage)), Scaling Factor:1', 'Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1', 'Prevalence Of Diarrhoea In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1', 'Prevalence Of Symptoms Of Acute Respiratory Infection (Ari) In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1', 'Registered Pregnancies For Which The Mother Received A Mother And Child Protection Card (Mcp)(%) (UOM:%(Percentage)), Scaling Factor:1', 'Population And Household Profile-Sex Ratio At Birth For Children Born In The Last Five Years (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1', 'Population And Household Profile-Sex Ratio Of The Total Population (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1', 'Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1', 'Fertility Rate (%) (UOM:%(Percentage)), Scaling Factor:1', 'Married Women Age Group 15 To 49 Years Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1', 'Infant And Child (Under Five Year) Mortality Rates (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 To 19 Years Who Were Already Mothers Or Pregnant At The Time Of The Survey (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 To 24 Years Who Use Hygienic Methods Of Protection During Their Menstrual Period (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 20 To 24 Years Married Before Age 18 Years (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Having A Mobile Phone That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Owning A House And Or Land (Alone Or Jointly With Others) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1', 'Men Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Are Overweight Or Obese (%)  (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Have Ever Used The Internet (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Worked In The Last 12 Months And Were Paid In Cash (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women With Body Mass Index (Bmi) Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Suffering From Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women Who Have Ever Undergone A Breast Examination For Breast Cancer (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women-Ever Undergone A Screening Test For Cervical Cancer (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Women-Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1', 'Young Women Age Group 18 To 29 Years Who Experienced Sexual Violence By Age18 (%) (UOM:%(Percentage)), Scaling Factor:1']

,Country,State,Year,Residence Type,Nfhs Survey Number (Nfhs - 4 Or Nfhs - 5),"Women Having A Bank Or Savings Account That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1","Adolescent Fertility Rate For Women Age 15 To 19 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Use Any Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Any Modern Family Planning Method (%) (UOM:%(Percentage)), Scaling Factor:1","Average Out Of Pocket Expenditure For Each Delivery In Public Health Facility (UOM:INR(IndianRupees)), Scaling Factor:1","Births Attended By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1","Births Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Births In Private Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Births In Public Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Either Vaccination Card Or Mothers Recall (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Vaccination Card Only (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Diphtheria Tetanus Toxoids And Pertussis (Dtp) Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Hepatitis B Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Polio Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Rotavirus Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received Bacillus Calmette Guerin (Bcg) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received The First Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Private Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Public Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 24 To 35 Months Who Have Received A Second Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 5 Years Who Attended Pre-Primary School During The Year 2019-20 (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 6 To 59 Months Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 6 To 8 Months Receiving Solid Or Semisolid Food And Breastmilk (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 9 To 35 Months Who Received Vitamin A Dose In The Last 6 Months (%) (UOM:%(Percentage)), Scaling Factor:1","Children Born At Home Who Were Taken To A Health Facility For A Check-Up Within 24 Hours Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Overweight (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Severely Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Stunted (Height-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Underweight (Weight-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 3 Years Breastfed Within One Hour Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 5 Years Whose Birth Was Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 6 Months Exclusively Breastfed (%) (UOM:%(Percentage)), Scaling Factor:1","Children Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Oral Rehydration Salts (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Zinc (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Fever Or Symptoms Of Acute Respiratory Infection In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Using Condom In The Age Group Of 15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Current Users Ever Told About Side Effects Of Current Method (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Who Usually Participate In Three Household Decisions (%) (UOM:%(Percentage)), Scaling Factor:1","Deaths In The Last 3 Years Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1","Ever-Married Women Age Group 18 To 49 Years Who Have Ever Experienced Spousal Violence (%) (UOM:%(Percentage)), Scaling Factor:1","Ever-Married Women Age Group 18 To 49 Years Who Have Experienced Physical Violence During Any Pregnancy (%) (UOM:%(Percentage)), Scaling Factor:1","Female Population Age 6 Years And Above Who Ever Attended School (%) (UOM:%(Percentage)), Scaling Factor:1","Female Sterilization Married Women-15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Health Worker Ever Talked To Female Non-Users About Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Home Births That Were Conducted By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1","Households Using Clean Fuel For Cooking (%) (UOM:%(Percentage)), Scaling Factor:1","Households Using Iodized Salt (%) (UOM:%(Percentage)), Scaling Factor:1","Population And Household Profile-Households With Any Usual Member Covered Under A Health Insurance Or Financing Scheme (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Using Intrauterine Device (Iud) Or Postpartum Intrauterine Contraceptive Device (Ppiud) As Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Infant Mortality Rate (Imr) (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Of Age 15 To 49 Years Using Injectables As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Institutional Births (%) (UOM:%(Percentage)), Scaling Factor:1","Institutional Births In Public Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Of Age 15 To 49 Years Using Male Sterlization As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 25 To 29 Years Married Before Age 21 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Are Overweight Or Obese (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have Ever Used Internet (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Men Whose Body Mass Index (Bmi) Is Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1","Men With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Elevated Blood Pressure Or Taking Medicine To Control Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Men-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Men-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Consumed Iron Folic Acid For 100 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Consumed Iron Folic Acid For 180 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Had An Antenatal Check-Up In The First Trimester (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Had At Least 4 Antenatal Care Visits (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Whose Last Birth Was Protected Against Neonatal Tetanus (%) (UOM:%(Percentage)), Scaling Factor:1","Neonatal Mortality Rate (Nnmr) (%) (UOM:%(Percentage)), Scaling Factor:1","Non-Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Non-Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Currently Married Women Age Group 15 To 49 Years Consuming Pill (%) (UOM:%(Percentage)), Scaling Factor:1","Population Below Age 15 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households That Use An Improved Sanitation Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households With An Improved Drinking Water Source (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households With Electricity (%) (UOM:%(Percentage)), Scaling Factor:1","Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Prevalence Of Diarrhoea In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Prevalence Of Symptoms Of Acute Respiratory Infection (Ari) In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Registered Pregnancies For Which The Mother Received A Mother And Child Protection Card (Mcp)(%) (UOM:%(Percentage)), Scaling Factor:1","Population And Household Profile-Sex Ratio At Birth For Children Born In The Last Five Years (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1","Population And Household Profile-Sex Ratio Of The Total Population (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1","Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Fertility Rate (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Infant And Child (Under Five Year) Mortality Rates (%) (UOM:%(Percentage)), Scaling Factor:1","Women Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 19 Years Who Were Already Mothers Or Pregnant At The Time Of The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 24 Years Who Use Hygienic Methods Of Protection During Their Menstrual Period (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 20 To 24 Years Married Before Age 18 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Women Having A Mobile Phone That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1","Women Owning A House And Or Land (Alone Or Jointly With Others) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Are Overweight Or Obese (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Ever Used The Internet (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Worked In The Last 12 Months And Were Paid In Cash (%) (UOM:%(Percentage)), Scaling Factor:1","Women With Body Mass Index (Bmi) Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1","Women With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Ever Undergone A Breast Examination For Breast Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Ever Undergone A Screening Test For Cervical Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Young Women Age Group 18 To 29 Years Who Experienced Sexual Violence By Age18 (%) (UOM:%(Percentage)), Scaling Factor:1"
0,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2019",Rural,NFHS-5,89.8,13,45.5,57.6,73.4,63.9,2089.0,97.8,20.2,NaN,15.8,12.4,84.8,96.8,92.1,88.4,87.4,0.7,95.9,85.5,0.0,100.0,28.6,33.7,33.3,NaN,87.2,NaN,5.2,4.6,26.4,31.1,19.0,47.8,97.8,NaN,91.8,NaN,NaN,NaN,64.6,8.2,80.5,95.5,88.8,13.2,0.5,81.8,44.6,31.0,0.4,71.0,99.7,1.6,5.0,8.4,0.1,98.7,92.1,0.3,41.9,66.4,25.6,20.4,5.8,50.6,33.4,41.1,53.7,62.2,1.6,47.7,9.1,17.1,6.6,31.2,4.0,22.1,6.4,80.7,41.0,73.5,81.0,88.5,89.0,2.8,NaN,57.7,4.5,19.7,88.0,95.3,96.5,55.5,5.1,3.1,97.9,891.0,929,10.6,1.2,10.3,9.5,4.3,7.6,41.1,4.0,99.1,15.3,80.9,19.4,85.6,94.7,35.7,18.4,27.9,80.7,72.5,17.1,8.2,47.6,6.7,16.2,7.3,26.4,2.6,2.8,10.2,16.9,4.8,2.2
1,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2019",Urban,NFHS-5,88.5,36,44.1,57.2,54.4,48.5,4230.0,96.7,40.8,NaN,33.6,24.3,72.1,NaN,93.1,83.0,75.7,0.0,100.0,79.3,5.7,90.9,34.6,NaN,47.8,NaN,84.3,NaN,5.7,5.1,18.2,15.1,12.8,45.8,96.9,NaN,90.0,NaN,NaN,NaN,81.0,12.1,88.0,93.0,94.8,23.2,0.0,86.5,31.0,30.1,0.0,95.6,99.7,1.4,2.2,NaN,0.5,99.2,81.8,0.0,33.8,44.7,NaN,9.2,NaN,37.0,36.8,54.6,61.3,67.5,7.8,59.4,9.5,19.4,8.6,28.2,3.5,17.6,6.5,81.2,64.8,81.2,86.0,89.4,92.8,NaN,NaN,57.4,2.2,22.7,88.0,98.0,99.5,NaN,6.2,0.0,100.0,941.0,1023,27.7,1.4,18.3,NaN,8.8,0.7,15.0,1.5,98.5,17.4,80.8,10.9,86.6,89.3,41.7,10.1,44.1,72.2,81.4,34.7,11.3,59.7,8.6,19.6,9.4,23.4,0.0,1.7,10.0,12.6,5.0,1.4
2,India,Andhra Pradesh,"Calendar Year (Jan - Dec), 2019",Rural,NFHS-5,79.6,80,59.1,59.3,71.2,71.1,3248.0,95.2,39.3,61.4,25.2,5.8,74.7,87.5,89.9,86.4,76.9,77.0,95.6,88.6,1.3,97.4,31.3,9.8,65.0,45.4,79.7,14.2,2.6,5.8,34.2,31.4,15.5,52.2,91.6,70.4,92.1,73.3,61.9,44.7,70.6,0.3,27.1,84.3,76.6,30.5,3.9,61.2,70.2,18.6,1.4,77.9,80.4,73.7,0.1,30.4,0.0,95.7,53.7,0.4,24.5,25.6,21.4,17.3,15.2,28.0,34.7,41.5,52.6,80.0,17.2,42.5,8.1,20.5,10.4,27.6,5.9,16.9,6.9,67.6,39.3,81.3,67.6,90.1,92.9,22.1,7.8,59.5,0.1,22.6,72.1,95.4,99.4,52.7,7.6,2.5,97.5,957.0,1055,6.3,1.8,4.4,35.8,2.8,0.6,4.7,14.1,82.5,32.9,40.9,50.6,63.8,76.3,32.6,22.6,15.4,47.2,59.7,44.5,16.2,34.3,7.0,17.9,9.2,24.3,0.8,4.8,6.8,13.2,5.8,3.7

In [25]:

NFHS_COLS = {
    'state_col':                'State',
    'women_with_bank_account':  'Women_Bank_Account_%',   
    'men_with_bank_account':    'Men_Bank_Account_%',     
    'female_literacy':          'Female_Literacy_%',
    'wealth_index_poorest':     'Wealth_Poorest_%',
    'female_workforce':         'Female_Workforce_%',
}

nfhs = nfhs_raw.rename(columns={v: k for k, v in NFHS_COLS.items()})
nfhs = nfhs.rename(columns={'state_col': 'state_name'})

print(nfhs['Nfhs Survey Number (Nfhs - 4 Or Nfhs - 5)'].unique())
print(nfhs['Residence Type'].unique())

num_cols = list(NFHS_COLS.keys())[1:]   
for col in num_cols:
    if col in nfhs.columns:
        nfhs[col] = pd.to_numeric(
            nfhs[col].astype(str).str.replace('%','').str.replace(',','').str.strip(),
            errors='coerce'
        )

# gender gap 
if 'men_with_bank_account' in nfhs.columns and 'women_with_bank_account' in nfhs.columns:
    nfhs['gender_gap'] = nfhs['men_with_bank_account'] - nfhs['women_with_bank_account']

print("Shape:", nfhs.shape)
nfhs.head()

['NFHS-5' 'NFHS-4']
['Rural' 'Urban' 'Total']
Shape: (108, 136)

,Country,state_name,Year,Residence Type,Nfhs Survey Number (Nfhs - 4 Or Nfhs - 5),"Women Having A Bank Or Savings Account That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1","Adolescent Fertility Rate For Women Age 15 To 19 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Use Any Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Any Modern Family Planning Method (%) (UOM:%(Percentage)), Scaling Factor:1","Average Out Of Pocket Expenditure For Each Delivery In Public Health Facility (UOM:INR(IndianRupees)), Scaling Factor:1","Births Attended By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1","Births Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Births In Private Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Births In Public Health Facility Delivered By Caesarean Section (%) (UOM:%(Percentage)), Scaling Factor:1","Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Either Vaccination Card Or Mothers Recall (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Fully Vaccinated Based On Information From Vaccination Card Only (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Diphtheria Tetanus Toxoids And Pertussis (Dtp) Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Penta Or Hepatitis B Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Polio Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received 3 Doses Of Rotavirus Vaccine (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received Bacillus Calmette Guerin (Bcg) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Have Received The First Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Private Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 12 To 23 Months Who Received Most Of Their Vaccinations In A Public Health Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 24 To 35 Months Who Have Received A Second Dose Of Measles Containing Vaccine (Mcv) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 5 Years Who Attended Pre-Primary School During The Year 2019-20 (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 6 To 59 Months Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 6 To 8 Months Receiving Solid Or Semisolid Food And Breastmilk (%) (UOM:%(Percentage)), Scaling Factor:1","Children Age Group 9 To 35 Months Who Received Vitamin A Dose In The Last 6 Months (%) (UOM:%(Percentage)), Scaling Factor:1","Children Born At Home Who Were Taken To A Health Facility For A Check-Up Within 24 Hours Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Overweight (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Severely Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Stunted (Height-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Underweight (Weight-For-Age) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under 5 Years Who Are Wasted (Weight-For-Height) (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 3 Years Breastfed Within One Hour Of Birth (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 5 Years Whose Birth Was Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1","Children Under Age 6 Months Exclusively Breastfed (%) (UOM:%(Percentage)), Scaling Factor:1","Children Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Oral Rehydration Salts (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Diarrhoea In The 2 Weeks Preceding The Survey Who Received Zinc (%) (UOM:%(Percentage)), Scaling Factor:1","Children With Fever Or Symptoms Of Acute Respiratory Infection In The 2 Weeks Preceding The Survey Taken To A Health Facility Or Health Provider (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Using Condom In The Age Group Of 15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Current Users Ever Told About Side Effects Of Current Method (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Who Usually Participate In Three Household Decisions (%) (UOM:%(Percentage)), Scaling Factor:1","Deaths In The Last 3 Years Registered With The Civil Authority (%) (UOM:%(Percentage)), Scaling Factor:1","Ever-Married Women Age Group 18 To 49 Years Who Have Ever Experienced Spousal Violence (%) (UOM:%(Percentage)), Scaling Factor:1","Ever-Married Women Age Group 18 To 49 Years Who Have Experienced Physical Violence During Any Pregnancy (%) (UOM:%(Percentage)), Scaling Factor:1","Female Population Age 6 Years And Above Who Ever Attended School (%) (UOM:%(Percentage)), Scaling Factor:1","Female Sterilization Married Women-15 To 49 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Health Worker Ever Talked To Female Non-Users About Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Home Births That Were Conducted By Skilled Health Personnel (%) (UOM:%(Percentage)), Scaling Factor:1","Households Using Clean Fuel For Cooking (%) (UOM:%(Percentage)), Scaling Factor:1","Households Using Iodized Salt (%) (UOM:%(Percentage)), Scaling Factor:1","Population And Household Profile-Households With Any Usual Member Covered Under A Health Insurance Or Financing Scheme (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Using Intrauterine Device (Iud) Or Postpartum Intrauterine Contraceptive Device (Ppiud) As Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Infant Mortality Rate (Imr) (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Of Age 15 To 49 Years Using Injectables As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Institutional Births (%) (UOM:%(Percentage)), Scaling Factor:1","Institutional Births In Public Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Of Age 15 To 49 Years Using Male Sterlization As One Of The Family Planning Methods (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 19 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 25 To 29 Years Married Before Age 21 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Are Overweight Or Obese (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have Ever Used Internet (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1","Men Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Men Whose Body Mass Index (Bmi) Is Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1","Men With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Men Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Elevated Blood Pressure Or Taking Medicine To Control Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Men-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Men-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Consumed Iron Folic Acid For 100 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Consumed Iron Folic Acid For 180 Days Or More When They Were Pregnant (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Had An Antenatal Check-Up In The First Trimester (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Had At Least 4 Antenatal Care Visits (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Who Received Postnatal Care From A Doctor Or Nurse Or Lady Health Visitor (Lhv) Or Auxiliary Nurse Midwifery (Anm) Or Midwife Or Other Health Personnel Within 2 Days Of Delivery (%) (UOM:%(Percentage)), Scaling Factor:1","Mothers Whose Last Birth Was Protected Against Neonatal Tetanus (%) (UOM:%(Percentage)), Scaling Factor:1","Neonatal Mortality Rate (Nnmr) (%) (UOM:%(Percentage)), Scaling Factor:1","Non-Breastfeeding Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Non-Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Currently Married Women Age Group 15 To 49 Years Consuming Pill (%) (UOM:%(Percentage)), Scaling Factor:1","Population Below Age 15 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households That Use An Improved Sanitation Facility (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households With An Improved Drinking Water Source (%) (UOM:%(Percentage)), Scaling Factor:1","Population Living In Households With Electricity (%) (UOM:%(Percentage)), Scaling Factor:1","Pregnant Women Age Group 15 To 49 Years Who Are Anaemic (%) (UOM:%(Percentage)), Scaling Factor:1","Prevalence Of Diarrhoea In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Prevalence Of Symptoms Of Acute Respiratory Infection (Ari) In The 2 Weeks Preceding The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Registered Pregnancies For Which The Mother Received A Mother And Child Protection Card (Mcp)(%) (UOM:%(Percentage)), Scaling Factor:1","Population And Household Profile-Sex Ratio At Birth For Children Born In The Last Five Years (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1","Population And Household Profile-Sex Ratio Of The Total Population (Females Per 1,000 Males) (UOM:Number), Scaling Factor:1","Children Age Group 6 To 23 Months Receiving An Adequate Diet (%) (UOM:%(Percentage)), Scaling Factor:1","Fertility Rate (%) (UOM:%(Percentage)), Scaling Factor:1","Married Women Age Group 15 To 49 Years Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Infant And Child (Under Five Year) Mortality Rates (%) (UOM:%(Percentage)), Scaling Factor:1","Women Unmet Need For Family Planning (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 Years And Above Who Consume Alcohol (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 Years And Above Who Use Any Kind Of Tobacco (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 19 Years Who Were Already Mothers Or Pregnant At The Time Of The Survey (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 24 Years Who Use Hygienic Methods Of Protection During Their Menstrual Period (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 20 To 24 Years Married Before Age 18 Years (%) (UOM:%(Percentage)), Scaling Factor:1","Women Having A Mobile Phone That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1","Women Owning A House And Or Land (Alone Or Jointly With Others) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1","Men Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Are Overweight Or Obese (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Comprehensive Knowledge Of Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Ever Used The Internet (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have High Risk Waist-To-Hip Ratio (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Know That Consistent Condom Use Can Reduce The Chance Of Getting Human Immunodeficiency Virus (Hiv) Or Acquired Immune Deficiency Syndrome (Aids) (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Worked In The Last 12 Months And Were Paid In Cash (%) (UOM:%(Percentage)), Scaling Factor:1","Women With Body Mass Index (Bmi) Below Normal (%) (UOM:%(Percentage)), Scaling Factor:1","Women With 10 Or More Years Of Schooling (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From High Or Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From Very High Blood Sugar Level (%) (UOM:%(Percentage)), Scaling Factor:1","Women Suffering From Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Women Who Have Ever Undergone A Breast Examination For Breast Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Ever Undergone A Screening Test For Cervical Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Ever Undergone An Oral Cavity Examination For Oral Cancer (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Mildly Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Women-Moderately Or Severely Elevated Blood Pressure (%) (UOM:%(Percentage)), Scaling Factor:1","Young Women Age Group 18 To 29 Years Who Experienced Sexual Violence By Age18 (%) (UOM:%(Percentage)), Scaling Factor:1"
0,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2019",Rural,NFHS-5,89.8,13,45.5,57.6,73.4,63.9,2089.0,97.8,20.2,NaN,15.8,12.4,84.8,96.8,92.1,88.4,87.4,0.7,95.9,85.5,0.0,100.0,28.6,33.7,33.3,NaN,87.2,NaN,5.2,4.6,26.4,31.1,19.0,47.8,97.8,NaN,91.8,NaN,NaN,NaN,64.6,8.2,80.5,95.5,88.8,13.2,0.5,81.8,44.6,31.0,0.4,71.0,99.7,1.6,5.0,8.4,0.1,98.7,92.1,0.3,41.9,66.4,25.6,20.4,5.8,50.6,33.4,41.1,53.7,62.2,1.6,47.7,9.1,17.1,6.6,31.2,4.0,22.1,6.4,80.7,41.0,73.5,81.0,88.5,89.0,2.8,NaN,57.7,4.5,19.7,88.0,95.3,96.5,55.5,5.1,3.1,97.9,891.0,929,10.6,1.2,10.3,9.5,4.3,7.6,41.1,4.0,99.1,15.3,80.9,19.4,85.6,94.7,35.7,18.4,27.9,80.7,72.5,17.1,8.2,47.6,6.7,16.2,7.3,26.4,2.6,2.8,10.2,16.9,4.8,2.2
1,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2019",Urban,NFHS-5,88.5,36,44.1,57.2,54.4,48.5,4230.0,96.7,40.8,NaN,33.6,24.3,72.1,NaN,93.1,83.0,75.7,0.0,100.0,79.3,5.7,90.9,34.6,NaN,47.8,NaN,84.3,NaN,5.7,5.1,18.2,15.1,12.8,45.8,96.9,NaN,90.0,NaN,NaN,NaN,81.0,12.1,88.0,93.0,94.8,23.2,0.0,86.5,31.0,30.1,0.0,95.6,99.7,1.4,2.2,NaN,0.5,99.2,81.8,0.0,33.8,44.7,NaN,9.2,NaN,37.0,36.8,54.6,61.3,67.5,7.8,59.4,9.5,19.4,8.6,28.2,3.5,17.6,6.5,81.2,64.8,81.2,86.0,89.4,92.8,NaN,NaN,57.4,2.2,22.7,88.0,98.0,99.5,NaN,6.2,0.0,100.0,941.0,1023,27.7,1.4,18.3,NaN,8.8,0.7,15.0,1.5,98.5,17.4,80.8,10.9,86.6,89.3,41.7,10.1,44.1,72.2,81.4,34.7,11.3,59.7,8.6,19.6,9.4,23.4,0.0,1.7,10.0,12.6,5.0,1.4
2,India,Andhra Pradesh,"Calendar Year (Jan - Dec), 2019",Rural,NFHS-5,79.6,80,59.1,59.3,71.2,71.1,3248.0,95.2,39.3,61.4,25.2,5.8,74.7,87.5,89.9,86.4,76.9,77.0,95.6,88.6,1.3,97.4,31.3,9.8,65.0,45.4,79.7,14.2,2.6,5.8,34.2,31.4,15.5,52.2,91.6,70.4,92.1,73.3,61.9,44.7,70.6,0.3,27.1,84.3,76.6,30.5,3.9,61.2,70.2,18.6,1.4,77.9,80.4,73.7,0.1,30.4,0.0,95.7,53.7,0.4,24.5,25.6,21.4,17.3,15.2,28.0,34.7,41.5,52.6,80.0,17.2,42.5,8.1,20.5,10.4,27.6,5.9,16.9,6.9,67.6,39.3,81.3,67.6,90.1,92.9,22.1,7.8,59.5,0.1,22.6,72.1,95.4,99.4,52.7,7.6,2.5,97.5,957.0,1055,6.3,1.8,4.4,35.8,2.8,0.6,4.7,14.1,82.5,32.9,40.9,50.6,63.8,76.3,32.6,22.6,15.4,47.2,59.7,44.5,16.2,34.3,7.0,17.9,9.2,24.3,0.8,4.8,6.8,13.2,5.8,3.7
3,India,Andhra Pradesh,"Calendar Year (Jan - Dec), 2019",Urban,NFHS-5,86.7,40,62.3,57.8,70.8,70.3,2659.0,98.3,50.5,66.1,30.9,15.2,69.3,89.1,84.8,83.0,70.6,72.0,92.4,83.7,11.5,86.4,27.1,10.2,58.7,67.3,81.7,NaN,3.0,6.4,23.1,25.1,17.6,51.6,93.8,61.4,92.9,77.6,64.2,32.8,69.2,0.9,33.6,83.4,89.4,28.8,3.5,75.5,68.3,18.6,1.0,96.6,89.3,62.2,0.2,29.8,0.0,98.6,41.8,0.6,20.5,15.8,12.8,13.8,13.1,37.7,47.1,65.1,53.8,88.4,15.0,59.5,9.2,24.9,13.7,32.2,7.3,19.2,7.4,76.7,45.6,82.7,67.2,92.2,92.5,14.4,19.5,57.8,0.1,21.3,89.1,99.4,99.6,56.2,6.2,2.0,94.2,877.0,1024,16.7,1.5,5.2,33.7,2.3,0.3,1.9,9.3,90.6,21.7,67.4,41.4,79.0,86.4,44.4,29.1,33.9,52.7,70.8,36.5,11.9,51.2,7.8,23.2,13.2,27.5,0.7,4.3,8.3,14.4,6.2,3.8
4,India,Arunachal Pradesh,"Calendar Year (Jan - Dec), 2019",Rural,NFHS-5,76.7,40,49.6,41.0,59.5,47.6,9649.0,80.3,14.4,43.8,17.4,23.4,64.6,76.9,76.8,71.8,68.8,32.4,87.1,80.1,0.7,97.3,27.1,5.5,57.1,49.5,68.8,1.9,9.7,6.8,27.9,15.8,13.6,51.7,87.4,62.9,54.8,52.6,63.1,26.9,45.9,4.2,73.9,86.6,33.4,26.0,3.3,69.0,18.7,19.0,4.1,46.3,99.2,28.5,6.2,12.3,1.0,77.3,73.6,0.0,54.3,51.4,25.6,21.5,21.5,26.6,34.0,68.5,45.7,79.1,4.6,45.0,6.8,11.9,4.3,33.1,0.7,22.8,9.1,22.9,7.9,52.4,34.6,54.6,76.1,6.9,12.8,41.6,15.9,27.2,83.4,92.9,94.0,28.6,5.3,2.0,95.2,990.0,998,21.4,1.9,12.3,18.3,6.9,25.9,19.7,6.6,91.4,19.3,75.3,70.3,69.0,84.5,22.9,12.5,49.6,69.4,62.9,23.6,5.7,36.2,4.6,8.2,3.0,24.8,0.3,0.7,0.5,16.5,6.7,0.8

In [26]:
# filter to NFHS-5 only
nfhs_5 = nfhs[nfhs['Nfhs Survey Number (Nfhs - 4 Or Nfhs - 5)'] == 'NFHS-5'].copy()

#  rename the columns before aggregating
nfhs_5 = nfhs_5.rename(columns={
    'Women Having A Bank Or Savings Account That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1': 'women_bank_account_pct',
    'Women Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1':               'female_literacy_nfhs',
    'Men Age Group 15 To 49 Years Who Are Literate (%) (UOM:%(Percentage)), Scaling Factor:1':                 'male_literacy_nfhs',
    'Women Who Worked In The Last 12 Months And Were Paid In Cash (%) (UOM:%(Percentage)), Scaling Factor:1':  'female_workforce_pct_nfhs',
    'Women Having A Mobile Phone That They Themselves Use (%) (UOM:%(Percentage)), Scaling Factor:1':          'women_mobile_pct',
    'Population Living In Households With Electricity (%) (UOM:%(Percentage)), Scaling Factor:1':              'electricity_access_pct',
    'Population Living In Households With An Improved Drinking Water Source (%) (UOM:%(Percentage)), Scaling Factor:1': 'clean_water_pct',
    'Women Owning A House And Or Land (Alone Or Jointly With Others) (%) (UOM:%(Percentage)), Scaling Factor:1': 'women_property_ownership_pct',
})

#  convert to numeric
num_cols_nfhs = ['women_bank_account_pct', 'female_literacy_nfhs',
                 'male_literacy_nfhs', 'female_workforce_pct_nfhs',
                 'women_mobile_pct', 'electricity_access_pct',
                 'clean_water_pct', 'women_property_ownership_pct']

for col in num_cols_nfhs:
    nfhs_5[col] = pd.to_numeric(nfhs_5[col], errors='coerce')

#  aggregate Rural + Urban → state total by averaging
nfhs_clean = nfhs_5.groupby('state_name')[num_cols_nfhs].mean().reset_index()

#  gender gap
nfhs_clean['literacy_gender_gap'] = nfhs_clean['male_literacy_nfhs'] - nfhs_clean['female_literacy_nfhs']
nfhs_clean.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleaned\nfhs_clean.csv", index=False)

print("NFHS cleaned shape:", nfhs_clean.shape)
print("States:", nfhs_clean['state_name'].tolist())
nfhs_clean.head()

NFHS cleaned shape: (36, 10)
States: ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'The Dadra and Nagar Haveli and Daman and Diu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

,state_name,women_bank_account_pct,female_literacy_nfhs,male_literacy_nfhs,female_workforce_pct_nfhs,women_mobile_pct,electricity_access_pct,clean_water_pct,women_property_ownership_pct,literacy_gender_gap
0,Andaman and Nicobar Islands,89.15,86.10,92.00,25.90,80.85,98.00,96.65,15.15,5.90
1,Andhra Pradesh,83.15,71.40,81.35,40.50,54.15,99.50,97.40,46.00,9.95
2,Arunachal Pradesh,81.35,75.95,87.95,23.30,78.60,96.75,95.50,70.05,12.00
3,Assam,79.90,81.45,87.70,18.25,64.65,95.25,88.65,40.10,6.25
4,Bihar,77.65,64.70,80.50,12.25,55.55,96.25,99.35,54.55,15.80

In [27]:
nfhs_clean['state_name'] = nfhs_clean['state_name'].str.title()

In [28]:
#RBI HANDBOOK 
rbi_path = r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\raw\Handbook.csv"
rbi_raw = pd.read_csv(rbi_path)
print("Shape:", rbi_raw.shape)
print("Columns:", rbi_raw.columns.tolist())
rbi_raw.head(3)

Shape: (813, 17)
Columns: ['Country', 'State', 'Year', 'Name Of The Region', 'Additional Info', 'Distribution Of Offices Of Scheduled Commercial Banks (UOM:Number), Scaling Factor:1', 'Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Sanction (UOM:Ratio), Scaling Factor:1', 'Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Utilisation (UOM:Ratio), Scaling Factor:1', 'Deposits By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Credit By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Credit To Agriculture By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Credit To Industry By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Personal Loans By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Deposits Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Credit Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Credit-Deposit Ratio Of Regional Rural Banks (UOM:Ratio), Scaling Factor:1', 'Number Of Branches Of Regional Rural Banks (UOM:Number), Scaling Factor:1']

,Country,State,Year,Name Of The Region,Additional Info,"Distribution Of Offices Of Scheduled Commercial Banks (UOM:Number), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Sanction (UOM:Ratio), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Utilisation (UOM:Ratio), Scaling Factor:1","Deposits By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Agriculture By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Industry By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Personal Loans By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Deposits Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit-Deposit Ratio Of Regional Rural Banks (UOM:Ratio), Scaling Factor:1","Number Of Branches Of Regional Rural Banks (UOM:Number), Scaling Factor:1"
0,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2025",Eastern Region,NaN,76.0,52.2,52.5,8549.0,4485.0,365.0,155.0,2975.0,NaN,NaN,NaN,NaN
1,India,Andhra Pradesh,"Calendar Year (Jan - Dec), 2025",Southern Region,NaN,8087.0,151.1,157.2,529673.0,832527.0,282319.0,89275.0,290337.0,52883.0,62573.0,118.3,1367.0
2,India,Arunachal Pradesh,"Calendar Year (Jan - Dec), 2025",North-Eastern Region,NaN,229.0,31.0,32.2,33114.0,10653.0,565.0,1021.0,7222.0,1511.0,515.0,34.1,34.0

In [29]:
RBI_COLS = {
    'state_name':           'State',
    'total_bank_branches': 'Total_Bank_Branches',
    'rural_branches':      'Rural_Branches',
    'urban_branches':      'Urban_Branches',
    'credit_deposit_ratio':'CD_Ratio',
}

rbi = rbi_raw.rename(columns={v: k for k, v in RBI_COLS.items()})


num_cols = ['total_bank_branches', 'rural_branches', 'urban_branches', 'credit_deposit_ratio']
for col in num_cols:
    if col in rbi.columns:
        rbi[col] = pd.to_numeric(
            rbi[col].astype(str).str.replace(',','').str.strip(),
            errors='coerce'
        )

rbi.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleanedrbi.csv", index=False)
print("Shape:", rbi.shape)
rbi.head()

Shape: (813, 17)

,Country,state_name,Year,Name Of The Region,Additional Info,"Distribution Of Offices Of Scheduled Commercial Banks (UOM:Number), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Sanction (UOM:Ratio), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Utilisation (UOM:Ratio), Scaling Factor:1","Deposits By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Agriculture By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Industry By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Personal Loans By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Deposits Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit-Deposit Ratio Of Regional Rural Banks (UOM:Ratio), Scaling Factor:1","Number Of Branches Of Regional Rural Banks (UOM:Number), Scaling Factor:1"
0,India,Andaman and Nicobar Islands,"Calendar Year (Jan - Dec), 2025",Eastern Region,NaN,76.0,52.2,52.5,8549.0,4485.0,365.0,155.0,2975.0,NaN,NaN,NaN,NaN
1,India,Andhra Pradesh,"Calendar Year (Jan - Dec), 2025",Southern Region,NaN,8087.0,151.1,157.2,529673.0,832527.0,282319.0,89275.0,290337.0,52883.0,62573.0,118.3,1367.0
2,India,Arunachal Pradesh,"Calendar Year (Jan - Dec), 2025",North-Eastern Region,NaN,229.0,31.0,32.2,33114.0,10653.0,565.0,1021.0,7222.0,1511.0,515.0,34.1,34.0
3,India,Assam,"Calendar Year (Jan - Dec), 2025",North-Eastern Region,NaN,3236.0,62.7,66.0,234070.0,154473.0,16325.0,25553.0,74641.0,12705.0,8107.0,63.8,475.0
4,India,Bihar,"Calendar Year (Jan - Dec), 2025",Eastern Region,NaN,8226.0,51.4,53.5,568726.0,304440.0,69932.0,33000.0,116048.0,47805.0,30493.0,63.8,2118.0

In [30]:
for name, df in [('PMJDY', pmjdy), ('Census', census_state), 
                 ('NFHS', nfhs), ('RBI', rbi)]:
    counts = df.groupby('state_name').size()
    max_rows = counts.max()
    print(f"{name}: {max_rows} rows per state (total rows: {len(df)})")

PMJDY: 1 rows per state (total rows: 36)
Census: 1 rows per state (total rows: 36)
NFHS: 3 rows per state (total rows: 108)
RBI: 43 rows per state (total rows: 813)

In [ ]:
# For bri, keeping only latest year per state
rbi_clean = rbi.sort_values('Year', ascending=False).drop_duplicates(subset='state_name', keep='first')

In [36]:
# MERGE
master = pmjdy.merge(census_state, on='state_name', how='left')
master = master.merge(nfhs_clean,  on='state_name', how='left')
master = master.merge(rbi_clean,         on='state_name', how='left')

# cross-dataset derived variables
master['accounts_per_capita'] = master['total_accounts'] / master['population']
if 'total_bank_branches' in master.columns:
    master['branches_per_lakh'] = (master['total_bank_branches'] / master['population']) * 100000

print("Shape:", master.shape)

missing_census = master[master['population'].isna()]['state_name'].tolist()
missing_nfhs   = master[master['women_bank_account_pct'].isna()]['state_name'].tolist()
print("\nStates missing Census data:", missing_census)
print("States missing NFHS data:",   missing_nfhs)

master.to_csv(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\data\cleaned\final_dataset.csv", index=False)
master.head()

Shape: (36, 56)

States missing Census data: []
States missing NFHS data: []

,sno,state_name,rural_accounts,urban_accounts,total_accounts,total_balance_crore,rupay_cards,total_balance,avg_balance_per_account,rupay_activation_ratio,rural_share,urban_share,households,population,male_pop,female_pop,literate_pop,male_literate,female_literate,sc_population,st_population,working_pop,female_working_pop,literacy_rate,male_literacy_rate,female_literacy_rate,female_workforce_pct,sc_share,st_share,avg_household_size,women_bank_account_pct,female_literacy_nfhs,male_literacy_nfhs,female_workforce_pct_nfhs,women_mobile_pct,electricity_access_pct,clean_water_pct,women_property_ownership_pct,literacy_gender_gap,Country,Year,Name Of The Region,Additional Info,"Distribution Of Offices Of Scheduled Commercial Banks (UOM:Number), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Sanction (UOM:Ratio), Scaling Factor:1","Credit-Deposit Ratio Of Scheduled Commercial Banks According To Place Of Utilisation (UOM:Ratio), Scaling Factor:1","Deposits By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit By Scheduled Commercial Banks In India (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Agriculture By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit To Industry By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Personal Loans By Scheduled Commercial Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Deposits Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit Of Regional Rural Banks (UOM:INR(IndianRupees)), Scaling Factor:10000000","Credit-Deposit Ratio Of Regional Rural Banks (UOM:Ratio), Scaling Factor:1","Number Of Branches Of Regional Rural Banks (UOM:Number), Scaling Factor:1",accounts_per_capita
0,1,Andaman And Nicobar Islands,46862,17645,64507,55.44,39096,5.544000e+08,8594.416110,0.606074,0.726464,0.273536,94551.0,380581.0,202871.0,177710.0,294281.0,164377.0,129904.0,0.0,28530.0,152535.0,31646.0,77.324144,81.025381,73.098869,17.807664,0.000000,7.496433,4.025140,89.15,86.10,92.00,25.90,80.85,98.00,96.65,15.15,5.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.169496
1,2,Andhra Pradesh,12453142,4607102,17060244,6464.17,10950935,6.464170e+10,3789.025526,0.641898,0.729951,0.270049,12718976.0,49577103.0,24830513.0,24746590.0,29859982.0,16549514.0,13310468.0,8469278.0,2740133.0,23080964.0,8573546.0,60.229380,66.649908,53.787079,34.645363,17.083043,5.527013,3.897885,83.15,71.40,81.35,40.50,54.15,99.50,97.40,46.00,9.95,India,"Calendar Year (Jan - Dec), 2025",Southern Region,NaN,8087.0,151.1,157.2,529673.0,832527.0,282319.0,89275.0,290337.0,52883.0,62573.0,118.3,1367.0,0.344115
2,3,Arunachal Pradesh,462544,11185,473729,301.90,318210,3.019000e+09,6372.841857,0.671713,0.976389,0.023611,270577.0,1383727.0,713912.0,669815.0,766005.0,439868.0,326137.0,0.0,951821.0,587657.0,237384.0,55.358102,61.613756,48.690609,35.440233,0.000000,68.786762,5.113986,81.35,75.95,87.95,23.30,78.60,96.75,95.50,70.05,12.00,India,"Calendar Year (Jan - Dec), 2025",North-Eastern Region,NaN,229.0,31.0,32.2,33114.0,10653.0,565.0,1021.0,7222.0,1511.0,515.0,34.1,34.0,0.342357
3,4,Assam,23230698,2602724,25833422,7838.20,16255078,7.838200e+10,3034.131522,0.629227,0.899250,0.100750,6305524.0,30771805.0,15715019.0,15056786.0,18818397.0,10376587.0,8441810.0,2206114.0,3868306.0,11800354.0,3390636.0,61.154674,66.029745,56.066481,22.518989,7.169271,12.570943,4.880134,79.90,81.45,87.70,18.25,64.65,95.25,88.65,40.10,6.25,India,"Calendar Year (Jan - Dec), 2025",North-Eastern Region,NaN,3236.0,62.7,66.0,234070.0,154473.0,16325.0,25553.0,74641.0,12705.0,8107.0,63.8,475.0,0.839516
4,5,Bihar,59890944,8663361,68554305,30049.94,49353085,3.004994e+11,4383.377528,0.719912,0.873628,0.126372,18913565.0,104099452.0,54278157.0,49821295.0,52504553.0,31608023.0,20896530.0,16567325.0,1336573.0,34724987.0,9502798.0,50.436916,58.233412,41.942968,19.073768,15.914901,1.283939,5.503957,77.65,64.70,80.50,12.25,55.55,96.25,99.35,54.55,15.80,India,"Calendar Year (Jan - Dec), 2025",Eastern Region,NaN,8226.0,51.4,53.5,568726.0,304440.0,69932.0,33000.0,116048.0,47805.0,30493.0,63.8,2118.0,0.658546

In [ ]:
# negative/impossible values fix
numeric_pct_cols = ['women_bank_account_pct', 'female_literacy_nfhs', 
                    'male_literacy_nfhs', 'electricity_access_pct',
                    'clean_water_pct', 'women_mobile_pct']
for col in numeric_pct_cols:
    if col in master.columns:
        master[col] = master[col].apply(lambda x: np.nan if pd.notna(x) and x < 0 else x)

print("Negative values fixed.")

Negative values fixed.

In [ ]:
print(master.groupby('state_name').size().describe())
# checking merge

count    36.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
dtype: float64

In [42]:
db_path = r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\database\pmjdy.db"
import os
os.makedirs(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\database", exist_ok=True)

conn = sqlite3.connect(r"C:\Users\Mihika\Desktop\dsm_project_final\dsm project\database\pmjdy.db")

pmjdy.to_sql('pmjdy_accounts',  conn, if_exists='replace', index=False)
census_state.to_sql('census_2011',   conn, if_exists='replace', index=False)
nfhs_clean.to_sql('nfhs_state',     conn, if_exists='replace', index=False)  # updated
rbi.to_sql('rbi_banking',      conn, if_exists='replace', index=False)
master.to_sql('master_dataset', conn, if_exists='replace', index=False)

cols = conn.execute("PRAGMA table_info(nfhs_state);").fetchall()
print("NFHS table columns:", [c[1] for c in cols])


# test join query 

join_query = """
SELECT 
    p.state_name,
    p.total_accounts,
    ROUND(p.rupay_activation_ratio, 3)  AS rupay_ratio,
    ROUND(p.avg_balance_per_account, 2) AS avg_balance,
    ROUND(c.literacy_rate, 1)           AS literacy_rate,
    ROUND(n.women_bank_account_pct, 1)  AS women_bank_pct,
    ROUND(n.literacy_gender_gap, 1)              AS gender_gap
FROM pmjdy_accounts p
LEFT JOIN census_2011  c ON p.state_name = c.state_name
LEFT JOIN nfhs_state   n ON p.state_name = n.state_name
ORDER BY p.rupay_activation_ratio DESC
LIMIT 10;
"""

result = pd.read_sql_query(join_query, conn)
conn.close()

print("\nTop 10 states by RuPay activation ratio:")
print(result.to_string(index=False))

NFHS table columns: ['state_name', 'women_bank_account_pct', 'female_literacy_nfhs', 'male_literacy_nfhs', 'female_workforce_pct_nfhs', 'women_mobile_pct', 'electricity_access_pct', 'clean_water_pct', 'women_property_ownership_pct', 'literacy_gender_gap']

Top 10 states by RuPay activation ratio:
                                  state_name  total_accounts  rupay_ratio  avg_balance  literacy_rate  women_bank_pct  gender_gap
                                       Delhi         7011342        0.777      5474.81           75.0            -6.3       -87.3
                                     Gujarat        19797888        0.764      6347.85           68.0            70.5        13.5
                                    Nagaland          412074        0.758      3746.90           67.9            66.7         7.1
                                 Lakshadweep           10681        0.752     19380.21           81.5            67.0         1.6
                              Madhya Pradesh        46878280        0.747      4046.77           59.0            75.9        13.2
                                   Rajasthan        38333545        0.744      6254.55           55.8            80.3        19.7
                                  Tamil Nadu        18783036        0.733      4184.61           71.8            92.2         6.5
                                      Odisha        23850358        0.728      5789.88           63.7            85.1        11.8
The Dadra And Nagar Haveli And Daman And Diu          245650        0.721      7991.86           70.1            83.7        15.7
                                       Bihar        68554305        0.720      4383.38           50.4            77.7        15.8